# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Croni < Formula
  desc "croni — A friendly CLI for managing scheduled jobs on macOS"
  homepage "https://github.com/dsaiztc/croni"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dsaiztc/croni/releases/download/v0.1.0/croni_0.1.0_darwin_amd64.tar.gz"
    sha256 "5ae751e6061f9decbced7f01e64b61a51a6a76002f4dc5c26ebc0e657bc8fdbf"

    define_method(:install) do
      bin.install "croni"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dsaiztc/croni/releases/download/v0.1.0/croni_0.1.0_darwin_arm64.tar.gz"
    sha256 "2dbf4bd2dafebc11eb47ca1f47b5152e45ce789a84df47e490fb9541984f6fa2"

    define_method(:install) do
      bin.install "croni"
    end
  end
end
