# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc "A CLI tool for managing development projects"
  homepage "https://github.com/dsaiztc/dev"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsaiztc/dev/releases/download/v0.4.0/dev_0.4.0_darwin_amd64.tar.gz"
      sha256 "2d59a42cf10f566441b7083bf3c649db32fcb7457fc85d9a9628c7699c2e5a01"

      define_method(:install) do
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsaiztc/dev/releases/download/v0.4.0/dev_0.4.0_darwin_arm64.tar.gz"
      sha256 "f27345565c556822a1fa206f5c2331cab639058fd957e539a836650d7c9e7882"

      define_method(:install) do
        bin.install "dev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiztc/dev/releases/download/v0.4.0/dev_0.4.0_linux_amd64.tar.gz"
      sha256 "8e854776316d9b9518a05f247bb97cc629e69a00f6501f70686a72b090db11f4"
      define_method(:install) do
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiztc/dev/releases/download/v0.4.0/dev_0.4.0_linux_arm64.tar.gz"
      sha256 "10de80d9d8eb622860ad0fee511abb395078a2e17cdb7cf93595d57150806dbd"
      define_method(:install) do
        bin.install "dev"
      end
    end
  end
end
