# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trl < Formula
  desc "trl — A modern CLI for Trello"
  homepage "https://github.com/dsaiztc/trl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsaiztc/trl/releases/download/v0.1.0/trl_0.1.0_darwin_amd64.tar.gz"
      sha256 "9d2962e300bb2943c9f6491905815c052c596d45990ebcbc0f149356e88f9c58"

      define_method(:install) do
        bin.install "trl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsaiztc/trl/releases/download/v0.1.0/trl_0.1.0_darwin_arm64.tar.gz"
      sha256 "3965196469b590ff49eaa190184532f080041bd55ae7127577bb81c91963ba10"

      define_method(:install) do
        bin.install "trl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiztc/trl/releases/download/v0.1.0/trl_0.1.0_linux_amd64.tar.gz"
      sha256 "d7269e7fb3b53f95667396eb926169025782c73f5ece389a7335a061f35f6991"
      define_method(:install) do
        bin.install "trl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiztc/trl/releases/download/v0.1.0/trl_0.1.0_linux_arm64.tar.gz"
      sha256 "941f36cd7feb3d3eace0bbb1577166954a72a1ff4b6e97b433dd77903c4248c6"
      define_method(:install) do
        bin.install "trl"
      end
    end
  end
end
